config/routes.rb
Rails.application.routes.draw do

  resources :ctfs do
    resources :challenges do
      get :dashboard, controller: :modules

      get 'spider', controller: :spider, action: :index
      post 'spider/run', controller: :spider, action: :run

      get 'dirb', controller: :dirb, action: :index
      post 'dirb/run', controller: :dirb, action: :run

      get 'wappalyzer', controller: :wappalyzer, action: :index
      post 'wappalyzer/run', controller: :wappalyzer, action: :run

    end
  end

  resources :modules, only: [:index]
  root 'pages#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord

  belongs_to :ctf, class_name: 'CTF'
  has_many :spiders
  has_many :dirbs
  has_many :wappalyzers

  validates :ctf, presence: true
  validates :name, uniqueness: true, presence: true, allow_blank: false
  validates :root, format: { with: URI.regexp, message: 'must be an URI' }

end

app/models/ctf.rb
class CTF < ApplicationRecord
  has_many :challenges

  validates :name, uniqueness: true, presence: true, allow_blank: false
end

app/models/dirb.rb
class Dirb < ApplicationRecord
  belongs_to :challenge
end

app/models/project.rb
class Project < ApplicationRecord

  has_many :spiders
  has_many :dirbs
  has_many :wappalyzers

  validates :name, uniqueness: true, presence: true, allow_blank: false
  validates :root, format: { with: URI.regexp, message: 'must be an URI' }

end

app/models/spider.rb
class Spider < ApplicationRecord
  belongs_to :challenge
end

app/models/wappalyzer.rb
class Wappalyzer < ApplicationRecord
  belongs_to :challenge
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :respond_to_html

  private

  def respond_to_html
    respond_to do |format|
      format.html { render template: 'pages/index' }
      format.all
    end
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def create
    ctf = CTF.find(params[:ctf_id])
    @challenge = ctf.challenges.create(challenge_params)
    if @challenge.errors.any?
      render json: @challenge.errors, status: 412
    else
      render json: @challenge
    end
  end

  def index
    ctf = CTF.find(params[:ctf_id])
    @challenges = ctf.challenges
    render json: @challenges
  end

  def show
    ctf = CTF.find(params[:ctf_id])
    @challenge = ctf.challenges.find(params[:id])
    render json: @challenge
  end

  private

  def challenge_params
    params.require(:challenge).permit(:name, :root)
  end
end

app/controllers/ctfs_controller.rb
class CTFsController < ApplicationController
  def create
    @ctf = CTF.create(ctf_params)
    if @ctf.errors.any?
      render json: @ctf.errors, status: 412
    else
      render json: @ctf.as_json(include: :challenges)
    end
  end

  def index
    @ctfs = CTF.all
    render json: @ctfs
  end

  def show
    @ctf = CTF.find(params[:id])
    render json: @ctf.as_json(include: :challenges)
  end

  private

  def ctf_params
    params.require(:ctf).permit(:name, :root)
  end
end

app/controllers/dirb_controller.rb
class DirbController < ModulesController
  DIRB_FILE = Rails.root.join('lib', 'modules', 'dirb.txt').to_s.freeze

  def run
    @challenge.dirbs.delete_all
    dirb = DirbService.new(root: @challenge.root, wordlist: DIRB_FILE)

    json = JSON.parse dirb.run
    json['links'].each do |link|
      url = link['url']
      content_type = link['content-type']
      @challenge.dirbs.find_or_create_by(url: url, 'content_type': content_type)
    end

    render json: @challenge.dirbs
  end

  def index
    render json: @challenge.dirbs
  end
end

app/controllers/modules_controller.rb
class ModulesController < ApplicationController
  before_action :load_params

  def dashboard
    render json: {}
  end

  private

  def load_params
    @challenge = Challenge.where(ctf_id: params[:ctf_id])
                          .find(params[:challenge_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/spider_controller.rb
class SpiderController < ModulesController

  def run
    @challenge.spiders.delete_all
    spider = SpiderService.new(root: @challenge.root)

    json = JSON.parse spider.run
    json['links'].each do |link|
      url = link['url']
      content_type = link['content-type']
      @challenge.spiders.find_or_create_by(url: url, 'content_type': content_type)
    end

    render json: @challenge.spiders
  end

  def index
    render json: @challenge.spiders
  end
end

app/controllers/wappalyzer_controller.rb
class WappalyzerController < ModulesController

  def run
    @challenge.wappalyzers.delete_all
    wappalyzer = WappalyzerService.new(root: @challenge.root)

    json = JSON.parse wappalyzer.run
    json['results']['applications'].each do |application|
      name = application['name']
      confidence = application['confidence']
      website = application['website']
      category = application['categories'][0]

      @challenge.wappalyzers.find_or_create_by(
        name: name,
        confidence: confidence,
        website: website,
        category: category
      )
    end

    render json: @challenge.wappalyzers
  end

  def index
    render json: @challenge.wappalyzers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ctfs/_form.html.erb
<%= form_for(ctf) do |f| %>
  <% if ctf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ctf.errors.count, "error") %> prohibited this ctf from being saved:</h2>

      <ul>
      <% ctf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ctfs/edit.html.erb
<h1>Editing Ctf</h1>

<%= render 'form', ctf: @ctf %>

<%= link_to 'Show', @ctf %> |
<%= link_to 'Back', ctfs_path %>

app/views/ctfs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>CTFs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ctfs.each do |ctf| %>
      <tr>
        <td><%= ctf.name %></td>
        <td><%= link_to 'Show', ctf %></td>
        <td><%= link_to 'Edit', edit_ctf_path(ctf) %></td>
        <td><%= link_to 'Destroy', ctf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ctf', new_ctf_path %>

app/views/ctfs/new.html.erb
<h1>New Ctf</h1>

<%= render 'form', ctf: @ctf %>

<%= link_to 'Back', ctfs_path %>

app/views/ctfs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ctf.name %>
</p>

<%= link_to 'Edit', edit_ctf_path(@ctf) %> |
<%= link_to 'Back', ctfs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubik</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag    'application' %>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>